spring:
  application:
    name: travel_service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useSSL=true&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  redis:
    host: ${TRAVEL_REDIS_HOST}
    port: ${TRAVEL_REDIS_PORT}
    password: ${TRAVEL_REDIS_PASSWORD}
    database: ${TRAVEL_REDIS_DATABASE}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
dubbo:
  registry:
    id: ${DUBBO_REGISTORY_ID}
    address: www.modutxt.xin:2181
    protocol: zookeeper
  protocol:
    port: 9090
    name: dubbo
    id: ${DUBBO_PROTOCOL_ID}
    status: server
  application:
    id: travel_service_id1
    name: travel_service_name1
  scan:
    base-packages: com.tip.travel.service.impl

travel:
  exception:
    db: ${TRAVEL_EXCEPTION_DB}
    email: ${TRAVEL_EXCEPTION_EMAIL}